# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yaaulyanenkovPW6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yaaulyanenkovPW6
  pod 'MyLogger3', :path => '../MyLogger3/'
end
